export const products = [
  {
    id: 1,
    name: "Basic Slim Fit T-Shirt",
    category: "T-Shirts",
    gender: "Men",
    color: "White",
    price: 199,
    sizes: ["XS", "S", "M", "L", "XL"],
    availability: "available",
    collection: "New",
    rating: 4.5,
    image: "/Group 64.png",
  },

  {
    id: 2,
    name: "Basic Heavy Weight T-Shirt",
    category: "T-Shirts",
    gender: "Men",
    color: "Black",
    price: 199,
    sizes: ["S", "M", "L", "XL"],
    availability: "available",
    collection: "Best Sellers",
    rating: 4.8,
    image: "/Rectangle 13.png",
  },

  {
    id: 3,
    name: "Full Sleeve Zipper",
    category: "Shirts",
    gender: "Men",
    color: "Green",
    price: 199,
    sizes: ["S", "M", "L", "XL"],
    availability: "available",
    collection: "New",
    rating: 4.2,
    image: "/Group 65.png",
  },

  {
    id: 4,
    name: "Oversized Cotton Tee",
    category: "T-Shirts",
    gender: "Women",
    color: "Brown",
    price: 179,
    sizes: ["XS", "S", "M", "L"],
    availability: "available",
    collection: "New",
    rating: 4.3,
    image: "/LastSec2.png",
  },

  {
    id: 5,
    name: "Relaxed Fit Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Black",
    price: 229,
    sizes: ["M", "L", "XL"],
    availability: "available",
    collection: "Best Sellers",
    rating: 4.7,
    image: "/Rectangle 18.png",
  },

  {
    id: 6,
    name: "Classic Cotton Tee",
    category: "T-Shirts",
    gender: "Women",
    color: "Grey",
    price: 189,
    sizes: ["XS", "S", "M", "L"],
    availability: "out",
    collection: "Essentials",
    rating: 4.1,
    image: "/Group 64.png",
  },

  {
    id: 7,
    name: "Minimal Polo Shirt",
    category: "Polo Shirts",
    gender: "Men",
    color: "White",
    price: 249,
    sizes: ["S", "M", "L", "XL"],
    availability: "available",
    collection: "New",
    rating: 4.6,
    image: "/Rectangle 13.png",
  },

  {
    id: 8,
    name: "Relaxed Summer Shirt",
    category: "Shirts",
    gender: "Women",
    color: "Beige",
    price: 219,
    sizes: ["S", "M", "L"],
    availability: "available",
    collection: "Summer",
    rating: 4.4,
    image: "/Group 65.png",
  },
];